services:
    aniliststream:
        build: .
        container-name: aniliststream
        ports:
            - "7000:7000"
        env_file:
            - .env
        depends_on:
            - redis
        restart: unless-stopped

    redis:
        image: redis:7-alpine
        container_name: aniliststream-redis
        command: redis-server --save "" --appendonly no --maxmemory 256mb --maxmemory-policy allkeys-lru --loglevel warning
        restart: unless-stopped
